spring:
  datasource:
    url: ${ORACLE_DATASOURCE_URL:jdbc:oracle:thin:@dinkdb_high}
    username: ${ORACLE_DATASOURCE_USERNAME:HANACARD}
    password: ${ORACLE_DATASOURCE_PASSWORD:Data2504}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 120000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 0
      initialization-fail-timeout: -1
      data-source-properties:
        oracle.jdbc.fanEnabled: false
        oracle.jdbc.autoCommitSpecCompliant: false
        oracle.jdbc.ReadTimeout: 120000
        oracle.net.CONNECT_TIMEOUT: 120000
        oracle.net.tns_admin: ${TNS_ADMIN:classpath:Wallet_DinkDB}
        oracle.net.wallet_location: "(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=${TNS_ADMIN:classpath:Wallet_DinkDB})))"
        oracle.net.ssl_server_dn_match: ${ORACLE_NET_SSL_SERVER_DN_MATCH:true}
        oracle.net.ssl_version: ${ORACLE_NET_SSL_VERSION:1.2}
        oracle.net.authentication_services: "(TCPS)"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

logging:
  level:
    com.kopo.hanacard: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    oracle.jdbc: INFO
    oracle.net: INFO
    oracle.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Oracle Cloud 특화 설정
oracle:
  cloud:
    wallet:
      location: ${TNS_ADMIN:classpath:Wallet_DinkDB}
      sso-enabled: true
    ssl:
      server-dn-match: ${ORACLE_NET_SSL_SERVER_DN_MATCH:true}
      version: ${ORACLE_NET_SSL_VERSION:1.2}
    connection:
      timeout: 120000
      read-timeout: 120000
